AdventureLookup/AdventureLookup

README.md
app/AppKernel.php
app/config/config.yml
app/config/routing.yml
composer.json

I added an initial admin backend using EasyAdmin. You can browse to [http://localhost:8000/app_dev.php/admin/](http://localhost:8000/app_dev.php/admin/) to see it (assuming you have content and can run the app locally).
Having an admin backend will make it MUCH easier to moderate the site. Currently, the only way to curate content is to scroll through the same frontend available to all users, and there is no way to add new users or add/change user roles as an admin. This is inefficient. A proper admin panel will give Matt, or whoever else acts as an admin, the ability to make more admins and mods to help share the curating load.
Currently, the initial admin does not feature any user authentication. Once we add that, we can define "mod" as a user role. Mods will be able to log into the …

Added initial admin backend integration

---

app/Resources/views/adventure/index.html.twig
app/Resources/views/base.html.twig
app/Resources/webpack/style.scss

Puts AdventureLookup/AdventureLookup#18 back in
The causes for alarm existed before this PR. I'll submit a PR that removes .vagrant from vcs.

Revert "Revert "Style adventure cards""

---

app/Resources/views/adventure/index.html.twig
app/config/security.yml
src/AppBundle/Controller/TagNameController.php
src/AppBundle/Entity/AdventureDocument.php
src/AppBundle/Service/FieldUtils.php

This adds an intermediate map between the info fields and their names. Therefore you are now able to use normalized field names in the adventure index and show templates.
I haven't changed anything in the database yet, but I think this is a good first step to make adjusting the index and show templates easier.
This will of course break if someone changes the title of one of the fields. Therefore I restricted access to the `/fields` and `/admin` interface to users with the `ROLE_ADMIN` role - which nobody currently has. It needs to be given manually to selected people by setting the `roles` column of the `users` table to `ROLE_USER,ROLE_CURATOR,ROLE_ADMIN `.
This should also fix the Frontend and make updating to the latest HEAD possible once more.
This also fixes #10.

Easy way to access adventure info

---

src/AppBundle/Entity/User.php

The BCrypt encoder we use to encode passwords [has a max password length of 72](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Core/Encoder/BCryptPasswordEncoder.php#L22). This updates the assertion accordingly, to display a proper error message when a user tries to register with a longer password.

Update max. password length assertion to match max. length accepted by encoder

---

app/Resources/views/adventure/index.html.twig
app/Resources/views/adventure/search_filter_tags.html.twig
app/Resources/views/adventure/search_filters.html.twig
app/Resources/views/adventure/search_results.html.twig
app/Resources/views/adventure/show.html.twig
app/Resources/views/security/login.html.twig
app/Resources/webpack/sass/search.scss
app/Resources/webpack/sass/style.scss
app/Resources/webpack/search.js
app/config/services.yml
src/AppBundle/Controller/AdventureController.php
src/AppBundle/Entity/AdventureDocument.php
src/AppBundle/Exception/FieldDoesNotExistException.php
src/AppBundle/Field/Field.php
src/AppBundle/Field/FieldProvider.php
src/AppBundle/Form/AdventureType.php
src/AppBundle/Service/AdventureSearch.php

This adds the search filters once again (fixes #55).
This also introduces a new `FieldProvider` service, which I already used inside the `AdventureSearch` service. This avoids having to re-define available fields and field names all over the place. Eventually, this should be used everywhere where fields are accessed.

Feature/#55 re-enable search filters

---

app/Resources/views/base.html.twig
app/config/config.yml
app/config/parameters.yml.dist

Fixes #63.
In your local installations, make sure to either execute `composer install` or copy `google_analytics_code: ~` into your `app/config/parameters.yml` file.

Make Google Analytics Code configurable

---

app/DoctrineMigrations/Version20170722192838.php
src/AppBundle/Entity/Adventure.php
src/AppBundle/Entity/AdventureDocument.php
src/AppBundle/Entity/Monster.php

This adds a really messy migration to update the data into the new format.
Using a migration was the easiest place for me to write the code.
I tested it using a MySQL dump from our dev site.
- Many adventures have multiple level ranges, which I simply concatenated for now
- Who added which field is currently lost, but could be re-added with some work if needed
- I moved "Villains" into the "Monsters" section and set 'unique' to true.
- The approval status of all fields is lost
There are a few TODOS left:
- The current live site has a new `Part Of` field, which we don't yet have
- Adventure 102 is ignored because it has two different editions
- Adventure 17 is ignored because it has multiple links
- I am not 100% sure about the boolean fields, inside the DB booleans are currently encoded …

[WIP] Feature/#67 migrate to new schema

---

src/AppBundle/Service/AdventureSearch.php

I must've broken it recently. 
Convert ArrayCollection to the simple array ElasticSearch expects.

Fix freetext search

---

src/AppBundle/DataFixtures/ORM/RandomAdventureData.php

`->words()` actually returns an array. Should've simply used `->catchphrase in the first place`.

Fix the 'Array to String' conversion notice triggered when loading the RandomAdventures fixture

---

src/AppBundle/Field/Field.php
src/AppBundle/Field/FieldProvider.php
src/AppBundle/Service/AdventureSearch.php

This, for example, allows you to find adventures with a monster called "goblin" by searching for "golbins" or "goblins".
It also prioritizes search results where the terms are found inside the title.

Use fuzziness for search, boost title field by 3

---

app/Resources/views/adventure/show.html.twig
src/AppBundle/Service/AdventureSearch.php

Use a local variable for the fieldname, otherwise the altered name is used in the next iteration of the loop.

Fix environment search links, fix field name for multiple search filters

---

app/config/config_prod.yml
app/config/parameters.yml.dist

Proof of concept to send critical errors via email. This follows https://symfony.com/doc/current/logging/monolog_email.html.
It is configured to send the same error at most every 60 minutes.
The receiver email addresses must be set in `app/config/parameters.yml`:
```yml
error_email_addresses:
- cmfcmf.flach@gmail.com
- ...
```
Here is a screenshot of an actual email sent from dev.adventurelookup.com where I provoked a server error by temporarily requesting a non-existing service:

Only log if critical error occurs, send critical errors via email

---

app/config/config_prod.yml

Each user triggers a debug log message saying their token was read from
the session. Normally, this would trigger an email per user. By telling
the deduplication handler to only consider logs > warning, it avoids
sending an email for every user encountering the error.

When checking for duplicated errors, only consider logs > warning

---

app/Resources/views/base.html.twig
app/Resources/webpack/adventure.js
src/AppBundle/Form/MonsterType.php

This should help prevent problems described in #100.
It also forces browsers to use the new asset version (I have already worked on automatic asset versioning, but this is something for a later PR. For now, just append an incrementing version to the query string).
This requires you to run `npm run prod` to come into effect.

Force browser cache busting, check for duplicate entities on creation / edit

---

app/AppKernel.php
app/Resources/views/audit/index.html.twig
app/Resources/webpack/sass/style.scss
app/config/config.yml
composer.json
composer.lock
src/AppBundle/Controller/AuditController.php

The log is really long and the page takes a while to load. This introduces a simple Bootstrap based pagination using the KnpPaginatorBundle. It also extends the `.pagination` class to center the pagination.

Paginate activity log using the KnpPaginatorBundle

---

app/Resources/views/adventure/search_results.html.twig
app/Resources/webpack/index.js
package.json

Currently, the search page loads dozens of images for every request. 
This PR uses https://github.com/verlok/lazyload to load them only if they scroll into view.
Eventually, we should limit the number of search results and only load new ones if you scroll to the bottom, but this is something I didn't want to tackle yet.

Lazy-load images

---

src/AppBundle/Listener/SearchIndexUpdater.php

Currently, deleting an adventure triggers an error:
> Uncaught PHP Exception Elasticsearch\Common\Exceptions\InvalidArgumentException: "id cannot be null." at /var/www/new.adventurelookup.com/html/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Client.php line 1549
This is because Doctrine sets the id of an entity to `null` before calling the `postRemove` callback.
The solution is to fill an array of ids of adventures being removed in the `preRemove` callback and delete all adventures in the `postFlush` callback.

Delete adventures correctly

---

.codecov.yml

They are pretty spammy and since we don't have many tests yet, are pretty meaningless as well. Code coverage is still visible as part of the PR status checks:

Disable CodeCov Bot comments

---

src/AppBundle/Entity/Adventure.php
src/AppBundle/Entity/Author.php
src/AppBundle/Entity/ChangeRequest.php
src/AppBundle/Entity/Edition.php
src/AppBundle/Entity/Environment.php
src/AppBundle/Entity/Item.php
src/AppBundle/Entity/Monster.php
src/AppBundle/Entity/MonsterType.php
src/AppBundle/Entity/Publisher.php
src/AppBundle/Entity/Setting.php
src/AppBundle/Entity/User.php
tests/AppBundle/Controller/RegistrationControllerTest.php

Currently, trying to create a user account with a long username or adding an adventure with a thumbnail url longer than 255 characters throws a 500 error, because the length is only enforced on the database and not on the forms. This PR adds a few `@Assert\Length` constraints to instead display a nice error message.
(for reference: coverage reports only appear because I branched of an old dev version)

Add assertions about max lengths of fields

---

src/AppBundle/Controller/ProfileController.php
tests/AppBundle/Controller/ProfileControllerTest.php
tests/Fixtures/ProfileTestData.php

Currently, once an own adventure only has resolved change requests, it vanishes from the profile page. This PR addresses fixes the behaviour reported in #158.

Show own adventures with only resolved change requests

---

app/DoctrineMigrations/Version20170814122644.php
app/Resources/views/change_request/show.html.twig
src/AppBundle/Controller/ChangeRequestController.php
src/AppBundle/Entity/ChangeRequest.php
src/AppBundle/Security/ChangeRequestVoter.php

Curators and an adventure's author can now add a remark to change requests, i.e. when they are invalid. The remark is visible to anyone who sees the change request.
refs #167

Add curator remarks to change requests

---

app/AppKernel.php
app/DoctrineMigrations/Version20170814102259.php
app/Resources/views/emails/reset_password.txt.twig
app/Resources/views/password_reset/do_reset.html.twig
app/Resources/views/password_reset/request_reset.html.twig
app/Resources/views/security/login.html.twig
app/config/config.yml
app/config/config_dev.yml
app/config/parameters.yml.dist
composer.json
composer.lock
src/AppBundle/Controller/PasswordResetController.php
src/AppBundle/Entity/User.php
src/AppBundle/Form/DoPasswordResetType.php
src/AppBundle/Form/RequestPasswordResetType.php
src/AppBundle/Form/UserType.php
src/AppBundle/Security/TokenGenerator.php
tests/AppBundle/Controller/PasswordResetControllerTest.php

This allows users to reset their passwords by providing their email address. and submitting a Google Recaptcha. The captcha is disabled in dev and test environments. The email is simply plaintext for now.
refs #31

Allow users to reset their passwords, configure Recaptcha bundle

---

app/Resources/views/adventure/index.html.twig
app/Resources/views/adventure/search_results.html.twig
app/Resources/webpack/index.js
app/Resources/webpack/search.js
src/AppBundle/Controller/AdventureController.php
src/AppBundle/Service/AdventureSearch.php

This limits the search results to 50 adventures per page - to reduce loading time, bandwidth and don't crash or freeze browsers on low-end systems. Note that this approach doesn't really take much load off of ElasticSearch - they recommend using the [Search After](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-search-after.html) API if you have a lot of results. However, it wasn't immediately obvious to me how I'd implement it correctly. The [from/size approach](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-from-size.html) will work for a maximum of 10.000 adventures, but I've added a hard limit of 5.000 for now.
This PR and #121 are the last things I see as important before we could push out another update, what do you …

Paginate adventure search using ElasticSearch from/size parameters

---

src/AppBundle/Field/FieldProvider.php

Link and thumbnail will now show up as available fields in the change request selector.
closes #171

Add missing link and thumbnail fields

---

src/AppBundle/Controller/AdventureController.php
src/AppBundle/Entity/MonsterType.php
tests/Browser/NewAdventureTest.php

Currently, if you create an adventure called 'new', the adventure's show route would be `/adventures/new`, which is the same as the route to create a new adventure. This would result in the adventure called 'new' not being possible to access. This PR changes the route to create new adventures to `/adventure`.
It also fixes a Typo I noticed.

Change /adventures/new route to /adventure

---

app/config/services.yml
scripts/deploy-to-dev.sh
scripts/update.sh

Otherwise
- the update fails if untracked files would be overridden (i.e. a previously generated `package-lock.json`
- the container compilation fails when it tries to autoload the fixture classes and the DoctrineFixtures library is not installed in production

Hotfix/use git --reset for updates, ignore DateFixtures for service discovery

---

app/Resources/views/adventure/search_results.html.twig
app/Resources/views/adventure/show.html.twig
src/AppBundle/Field/FieldProvider.php
src/AppBundle/Form/AdventureType.php

This does not rename the field from at the code side / datastructures, because I didn't want to rename everything again if we decided to rename the field once more. Proper renaming throughout the code should be done once things calm down and the field names don't change anymore.
closes #191

Rename tactical maps to battle mats

---

Vagrantfile
app/Resources/views/adventure/show.html.twig
app/config/parameters.yml.dist
app/config/services.yml
composer.json
composer.lock
src/AppBundle/Twig/AppExtension.php
tests/Twig/AppExtensionTest.php

New affiliate codes can be added via the `app/config/parameters.yml` file and must follow the format described here https://github.com/AdventureLookup/AdventureLookup/compare/dev...cmfcmf:feature/177-affiliate-code-logic?expand=1#diff-b21427cb85d0a014d5856b811168ad74R33.
This will require you to install the PHP mbstring and intl extensions:
sudo apt install php7.0-mbstring php7.0-intl
closes #177 
@JohnnyFlash does this add all the functionality we need?

Add ability to add affiliate codes to urls

---

src/AppBundle/Entity/Adventure.php
tests/AppBundle/Entity/AdventureTest.php

It looks like currently you cannot set edition, publisher or setting to null after you set them to something else.

Let setEdition, setPublisher and setSetting accept null

---

app/DoctrineMigrations/Version20170816131325.php
app/DoctrineMigrations/Version20170818080730.php
src/AppBundle/Controller/CurationController.php
src/AppBundle/Repository/AdventureRepository.php
tests/AppBundle/Repository/AdventureRepositoryTest.php

- Split migration to avoid implicit DDL commits (MySQL commits automatically after DDL changes, if the following DML query fails, the migration cannot completely be rolled back)
- improve createdAt detection, previously didn't return a result for some adventures (query runs for ~90 seconds at dev server)
- fix another edge case related to common/boss monsters...
I have already tested an update from master to this branch on the dev server.

Fixes a few bugs introduced in the bulk edit update

---

app/Resources/views/adventure/search_filters.html.twig
app/Resources/views/adventure/search_results.html.twig
app/Resources/webpack/search.js

- "Load more results" button disables with an info message if no more adventures are available.
- Fields not in the explicit filter list but in the search criteria from other pages are retained on the main page through hidden form input elements.
- Fields visible for rendering in filters on the main page are managed in a list.

Fix for issue #210

---

app/Resources/webpack/sass/search.scss

Add a new class to search sass to remove bottom margins from the check boxes.

Remove bottom margins from checkbox filters for compactness. Issue #199.

---

app/Resources/views/adventure/index.html.twig

Fixed the wording of the search instructions on the homepage to 
`Seperate distinct search terms with a <code>,</code>. Results will include all search terms.`
Are we happy with this? This is my first PR!
Fixes #125

Fixed wording for search instructions

---

Vagrantfile

During my initial efforts to stand up AdventureLookup locally I ran into the issue outlined in https://github.com/AdventureLookup/AdventureLookup/issues/243.
I believe it has something to do with the handling of users/groups on the VM and how Symfony stores sessions on disk in dev. The writing of the sessions is denied, and thus the app does not work.
Since NFS is not used by the Windows developers (current active devs as far as I understand) I would suggest removing this since it doesn't work, and if someone wants to add it back they can solve the underlying problem.

Remove nfs from Vagrantfile for non-windows users

---

app/Resources/views/base.html.twig

Old link lacked the `https://`, and so ultimately linked to `https://www.adventurelookup.com/adventures/twitter.com/mattcolville`, which... is not a thing.

fix link to Matt Coleville's twitter

---

Vagrantfile
scripts/install-composer.sh

Make a few improvements to the vagrant box, 
- Make the installation quieter
- Composer was not correctly downloaded any longer, use the recommended script to download composer
- Added a 2GB swap file, because the memory isn't sufficient for some composer commands
- Fixed PhantomJS installation by installing the missing `libfontconfig1` package
- Increased PHP realpath cache size, which should speed things up a bit
- Replaced `apt` by `apt-get` to remove warnings about unstable command line interface

Correctly download composer, make install quieter, add composer plugins

---

src/AppBundle/Controller/AdventureController.php
tests/AppBundle/Controller/AdventureControllerTest.php

Sometimes users supply a non-array as `$filters` argument, which results in a server error. This fixes the behaviour by silently discarding the `$filters` argument.

Validate the $filter argument to be an array

---

.travis.yml
README.md
Vagrantfile
composer.json
composer.lock
phpunit.xml.dist
scripts/prepare-browser-tests.sh
scripts/start-phantomjs.sh
tests/AppBundle/Curation/BulkEditFormHandlerTest.php
tests/AppBundle/Curation/BulkEditFormProviderTest.php
tests/AppBundle/Entity/AdventureTest.php
tests/AppBundle/Repository/AdventureRepositoryTest.php
tests/AppBundle/Security/AdventureListVoterTest.php
tests/AppBundle/Twig/AppExtensionTest.php
tests/Browser/NewAdventureTest.php
tests/BrowserTestCase.php

I just couldn't get PhantomJS to work reliably and fast enough. Additonally, PhantomJS has officially been abandoned a few days ago: https://github.com/ariya/phantomjs/issues/15344
This is why I decided to switch to Google Chrome in headless mode. Tests run lightning fast (compared to PhantomJS) and in a real browser.
While I was at it, I also moved all the linting into a separate travis build.

Switch to Google Chrome headless instead of PhantomJS for browser tests

---

app/Resources/webpack/js/index.js
app/Resources/webpack/sass/_filter.scss
app/Resources/webpack/sass/style.scss
app/Resources/webpack/sass/vendor/bootstrap.scss
app/Resources/webpack/sass/vendor/fontawesome.scss
app/Resources/webpack/sass/vendor/selectize.scss
package-lock.json
package.json
scripts/prepare-browser-tests.sh
tests/Browser/NewAdventureTest.php

This fixes ~~part of~~ #263 by 
1. removing `font-awesome-webpack`: It caused the FontAwesome css to not be included inside the css files, but rather be manually written by JavaScript.
2. moving all styles except the main `style.scss` entrypoint from the JavaScript file for consistency.
I have temporarily deployed this to https://dev.adventurelookup.com/adventures/. I don't see any lag in icon rendering any longer (except on the very first, un-cached page load).

Remove usage of font-awesome-webpack, remove all style imports from JS

---

package-lock.json
package.json

It was rather difficult to update the `hoek` package, because newer `node-sass` versions require a specific version of the `request` package which in-turn doesn't allow the newer `hoek` version. That's why I had to fix `node-sass` to `4.6.1`. 
Note: This pull request is intentionally not to the `dev` branch, but to the `master` branch to be able to apply it directly to the live site. When this is merged, I'll create another pull request back from `master` into `dev` to also apply the fix to the `dev` branch.
This fixes #270.

Update dependencies to mitigate security issue with hoek package

---

app/Resources/TwigBundle/views/Exception/error.html.twig
app/Resources/TwigBundle/views/Exception/error403.html.twig
app/Resources/TwigBundle/views/Exception/error404.html.twig

Here is an example of how it looks like:
Symfony Docs: https://symfony.com/doc/current/controller/error_pages.html#overriding-the-default-error-templates

Customize error pages to use our design

---

app/Resources/views/change_request/show.html.twig
app/Resources/views/profile/overview.html.twig
app/Resources/webpack/js/index.js
app/Resources/webpack/js/paginated_list_group.js
src/AppBundle/Controller/ProfileController.php
tests/AppBundle/Controller/ProfileControllerTest.php

- Avoid long scrolling if you have many adventures / change requests (closes #224)
- Show resolved own change requests (closes #223)
@WillSave what do you think?

Improve profile overview

---

README.md
app/config/services.yml
composer.lock
scripts/prepare-browser-tests.sh
src/AppBundle/Twig/AppExtension.php
tests/AppBundle/Twig/AppExtensionTest.php
tests/Browser/NewAdventureTest.php

We need to cache the `$rules` using a Symfony cache adapter, otherwise the vendor library tries to cache them inside the `vendor` folder, where it doesn't have permission to do so, resulting in errors.

Update league/uri and specify cache explicitly.

---

app/Resources/views/adventures/index.html.twig
app/Resources/views/adventures/search_results.html.twig
app/Resources/views/api/docs.html.twig
app/Resources/webpack/js/adventures_filter.jsx
app/Resources/webpack/js/adventures_filter/Root.jsx
app/Resources/webpack/js/adventures_filter/SearchBox.jsx
app/Resources/webpack/sass/_adventures.scss
src/AppBundle/Command/AppElasticsearchReindexCommand.php
src/AppBundle/Controller/AdventureController.php
src/AppBundle/Controller/ApiController.php
src/AppBundle/Entity/AdventureDocument.php
src/AppBundle/Listener/SearchIndexUpdater.php
src/AppBundle/Service/AdventureSearch.php
src/AppBundle/Service/AdventureSerializer.php
src/AppBundle/Service/TimeProvider.php
tests/AppBundle/Service/AdventureSearchTest.php
tests/AppBundle/Service/AdventureSerializerTest.php
tests/AppBundle/Service/TimeProviderTest.php

This PR allows sorting results like requested in #179.
The new 'Sort by' dropdown allows sorting by
- Best match: default ElasticSearch sorting/scoring based on queries and filter
- Reviews: Wilson-Score of the positive and negative reviews. For an explanation of the scoring, you can read [this section](https://github.com/msn0/wilson-score-interval#less-technical).
- Most and least pages
- Recently and least recently added
- Random
<a href="https://gitpod.io/#https://github.com/AdventureLookup/AdventureLookup/pull/307"><img src="https://gitpod.io/api/apps/github/pbs/github.com/cmfcmf/AdventureLookup.git/f6d09b2794812270b520b3b71f4713858269c472.svg" /></a>

Allow to sort results

---

app/Resources/views/base.html.twig
app/Resources/webpack/sass/_announcement.scss
app/Resources/webpack/sass/style.scss
app/config/config.yml
app/config/parameters.yml.dist

Adds a bar for global announcements. The text is defined by the `announcement` parameter in `app/config/parameters.yml`.
I'm not familiar with the framework, so please let me know if anything isn't quite how it's supposed to be :)
<a href="https://gitpod.io/#https://github.com/AdventureLookup/AdventureLookup/pull/319"><img src="https://gitpod.io/api/apps/github/pbs/github.com/wetterlicht/AdventureLookup.git/056e5fc3a63710d95d82699c0f2d2857d56d5775.svg" /></a>

Add global announcement bar

---

src/AppBundle/DataFixtures/ORM/RandomAdventureData.php

This fixes an issue where creating the random adventure data would sometimes fail if the same title is generated twice (the title column has a unique index in the database).
<a href="https://gitpod.io/#https://github.com/AdventureLookup/AdventureLookup/pull/335"><img src="https://gitpod.io/api/apps/github/pbs/github.com/cmfcmf/AdventureLookup.git/b481bed56a561a0e13cf1983b161b4789a1aa8a7.svg" /></a>

Generate unique titles for random adventures

---

app/Resources/views/adventure/_details.html.twig
app/Resources/views/adventure/index.html.twig
app/Resources/webpack/sass/_adventure.scss

I made the alignment of the bookmark dropdown depending on the screen size, as on tablets the button is to the left.
I implemented the rows/columns as suggested and I think it looks good on mobile. Not quite sure if its a bit too empty now on bigger screens but I think semantically the rows make sense like this.
<a href="https://gitpod.io/#https://github.com/AdventureLookup/AdventureLookup/pull/334"><img src="https://gitpod.io/api/apps/github/pbs/github.com/wetterlicht/AdventureLookup.git/cf21623ae820305c387df41b69737336b4ee0d43.svg" /></a>

Minor stylistic improvements to adventure details page

---

app/Resources/views/adventure/_reviews.html.twig
app/Resources/views/adventure/index.html.twig
app/Resources/webpack/sass/_adventure.scss
app/Resources/webpack/sass/_filter.scss

Adjust filter buttons, move review save and cancel buttons inside review form. 
* Making the filter buttons marginally larger to accommodate easier mobile use without hitting filter when you meant to see more and vice-versa
* Move review buttons inside review form so that save and cancel buttons are more intuitively placed, especially on mobile.
Filters:
OLD: 
NEW:
Reviews:
OLD:
NEW:
<a href="https://gitpod.io/#https://github.com/AdventureLookup/AdventureLookup/pull/342"><img src="https://gitpod.io/api/apps/github/pbs/github.com/Wigginns/AdventureLookup.git/dd455284e1692aae23913f7469f941d297290fc9.svg" /></a>

Filter button sizes and review button placement changes

---

app/Resources/views/adventure/_details.html.twig
app/Resources/webpack/js/adventure.js
app/config/services.yml
src/AppBundle/Form/Type/AdventureType.php
src/AppBundle/Service/AffiliateLinkHandler.php
src/AppBundle/Twig/AppExtension.php
tests/AppBundle/Service/AffiliateLinkHandlerTest.php
tests/AppBundle/Twig/AppExtensionTest.php

This PR adds a little disclaimer to our affiliate links and also explains that automatically add affiliate parameters to certain URLs.
I extracted the affiliate link handling into a separate service and added a `getDomains` method.
<a href="https://gitpod.io/#https://github.com/AdventureLookup/AdventureLookup/pull/361"><img src="https://gitpod.io/api/apps/github/pbs/github.com/cmfcmf/AdventureLookup.git/be080150e920ec7f210f3481fc341d1542fd978a.svg" /></a>

Explicitly mark our affiliate links

---

app/Resources/views/adventures/search_results.html.twig
app/Resources/views/api/docs.html.twig
app/Resources/webpack/js/adventures_filter/Filters.jsx
app/Resources/webpack/js/adventures_filter/Root.jsx
app/Resources/webpack/js/adventures_filter/SearchTags.jsx
app/Resources/webpack/js/adventures_filter/StringFilter.jsx
app/Resources/webpack/js/adventures_filter/field-util.js
app/Resources/webpack/sass/_adventures.scss
app/Resources/webpack/sass/_filter.scss
src/AppBundle/DataFixtures/ORM/RandomAdventureData.php
src/AppBundle/Service/AdventureSearch.php
tests/AppBundle/Service/AdventureSearchTest.php

This PR allows you to filter by adventures where a field is `null`. For example, you can now choose to include adventure with an unknown number of pages if you filter by number of pages:
Additionally, search tags now indicate more clearly whether they are ORed or ANDed.
Boolean fields now also show a blue bubble with the number of adventures that selected "yes" and "no". These numbers are only shown as long as "all" is selected. This is because the number of adventures that have "no" is always 0 when filtering for "yes" and vice versa.
I also changed the URL behavior slightly once again.
It also fixes the following bug:
> To reproduce, select "soloable = yes", then apply.
> Then select "soloable = all" -> the soloable filter disappears before you apply.
<a …

Add option to filter by "unknown", add counts to boolean fields

---

src/AppBundle/Controller/AdventureController.php
src/AppBundle/Controller/ApiController.php
tests/AppBundle/Controller/AdventureControllerTest.php
tests/AppBundle/Controller/ApiControllerTest.php
tests/AppBundle/Controller/DefaultControllerTest.php
tests/AppBundle/Controller/SecurityControllerTest.php

There is no need for the trailing slash and it looks ugly, especially when combined with the new URL-based search filters. This PR removes the trailing slash but adds a fallback layer since most links out in the wild include a trailing slash. I also removed the no longer needed "POST" method, since parameters are now always part of the URL.
<a href="https://gitpod.io/#https://github.com/AdventureLookup/AdventureLookup/pull/355"><img src="https://gitpod.io/api/apps/github/pbs/github.com/cmfcmf/AdventureLookup.git/30ffa423e1eaeaea377db5074bf680be58cbcf75.svg" /></a>

Remove trailing slash on /adventures route

---

app/DoctrineMigrations/Version20200607073617.php
app/DoctrineMigrations/Version20200607073734.php

The first migration is auto-generated. I'm not sure why it insists on updating the name of the index, but I also checked on the prod server and it wants to generate the same migration.
The second migration closes #39 by changing the charset and collation of all tables that still use `utf8` to `utf8mb4`.
You can verify that this worked by
- trying to add an adventure with an emoji in its title (fails without this migration)
- executing `SHOW TABLE STATUS` and `SHOW FULL COLUMNS FROM TABLE_NAME_HERE;` in the mysql console (`mysql -uroot -proot adl`) before and after running the migration.
<a href="https://gitpod.io/#https://github.com/AdventureLookup/AdventureLookup/pull/356"><img src="https://gitpod.io/api/apps/github/pbs/github.com/cmfcmf/AdventureLookup.git/4603fa0cf3414ec29a2ebf0d45d1e36 …

Update charset of existing tables to utf8mb4

---

.travis.yml
Procfile
README.md
app.json
app/AppKernel.php
app/config/config.yml
app/config/config_heroku.yml
app/config/parameters.yml.dist
app/config/services.yml
composer.json
composer.lock
package.json
scripts/heroku-nginx.conf
scripts/update.sh
src/AppBundle/Controller/AdventureController.php
src/AppBundle/DataFixtures/ORM/RandomAdventureData.php
src/AppBundle/DataFixtures/ORM/TestUserData.php
src/AppBundle/Entity/User.php
src/AppBundle/Service/AdventureSearch.php
src/AppBundle/Service/ElasticSearch.php
tests/AppBundle/Service/ElasticSearchTest.php
web/app_heroku.php

This PR sets up Heroku review apps. Review apps are created for every PR and allow testing PRs more easily. To make AdventureLookup run on Heroku, only minor changes have been necessary:
- Use ElasticSearch instead of MySQL for random adventures (Heroku uses PostgreSQL instead of MySQL)
- Install fixture bundle in production (Heroku does not install dev dependencies, and we need the fixture bundle for dummy adventures)
- Make ElasticSearch host configurable
- Rename npm `prod` script to `build`, as expected by Heroku
- Create less sample adventures to not run into memory and database limits
<a href="https://gitpod.io/#https://github.com/AdventureLookup/AdventureLookup/pull/369"><img src="https://gitpod.io/api/apps/github/pbs/github.com/cmfcmf/AdventureLookup.git/9c5785ac0277d048e39b8b629d6 …

Deploy PRs to Heroku

---

README.md
src/AppBundle/DataFixtures/ORM/RealAdventureData.php

Sometimes it's nice to work with real adventure data. I added a fixture that loads 200 adventures from adventurelookup.com using the REST API.
<a href="https://gitpod.io/#https://github.com/AdventureLookup/AdventureLookup/pull/368"><img src="https://gitpod.io/api/apps/github/pbs/github.com/cmfcmf/AdventureLookup.git/4a4c90006e582bd3ac47d5dfc05bb74005810921.svg" /></a>

Add fixture that loads real adventures from adventurelookup.com

---

app/Resources/webpack/sass/_general.scss

This PR fixes a visual bug introduced by #379:
We cannot directly change the color of all card links, because that overwrites the color used by, e.g., buttons, list groups, etc. Instead, we simply change the link color globally, which _can_ be overwritten by other components.

Fix link color

---

app/Resources/views/adventure/_details.html.twig
app/Resources/views/footer.html.twig
app/Resources/webpack/sass/_adventure.scss
app/config/config.yml

I feel like a disclaimer that explicitly states that all data displayed on AdventureLookup.com comes without warranty and may be incomplete or wrong is a good thing to have.
If you have suggestions for improved wording, let me know.
<a href="https://gitpod.io/#https://github.com/AdventureLookup/AdventureLookup/pull/387"><img src="https://gitpod.io/api/apps/github/pbs/github.com/cmfcmf/AdventureLookup.git/55627ea50243452a7dfc57e453be22ee348152c0.svg" /></a>

Add disclaimer that data may be wrong

---

app/Resources/webpack/js/adventures_filter.jsx
src/AppBundle/Field/Field.php
src/AppBundle/Field/FieldProvider.php
tests/AppBundle/Field/FieldTest.php
tests/AppBundle/Service/AdventureSerializerTest.php

I feel like the current sort order of filters in the search filter bar is not ideal. For example, I doubt that many people want to search by adventure author, yet the author field is the first filter field. This PR adds a new paramter to fields to control the sort order in the filter bar.
I also renamed "Includes pregenerated characters" to "Has pregenerated characters" so that it no longer needs two lines.
| Before | After |
| ------ | ----- |
| ![image](https://user-images.githubusercontent.com/2145092/88270661-43c0d500-ccd6-11ea-8a47-13facb9ee29f.png)| ![image](https://user-images.githubusercontent.com/2145092/88270656-41f71180-ccd6-11ea-9b3c-4ce05d1ddc5f.png) |
Let me know what you think of the new ordering.
<a href="https://gitpod.io/#https://github.com/AdventureLookup/AdventureLookup …

Make sort order of fields in filter bar configurable
