app/Resources/views/adventure/new.html.twig

Added message requiring D&D-only systems

---

app/Resources/views/adventure/index.html.twig
app/Resources/views/base.html.twig
app/Resources/webpack/style.scss

Reverts AdventureLookup/AdventureLookup#14

Revert "Style adventure cards"

---

package.json

Add production build option for webpack

---

README.md

Forgot to remove a line in the edited README

---

app/DoctrineMigrations/Version20170720173952.php
app/DoctrineMigrations/Version20170720200544.php
app/Resources/views/adventure/index.html.twig
app/Resources/views/adventure/show.html.twig
app/Resources/webpack/style.scss
app/config/services.yml
src/AppBundle/Command/AppElasticsearchReindexCommand.php
src/AppBundle/DataFixtures/ORM/RandomAdventuresData.php
src/AppBundle/DataFixtures/ORM/TagData.php
src/AppBundle/Entity/Adventure.php
src/AppBundle/Entity/AdventureDocument.php
src/AppBundle/Form/AdventureType.php
src/AppBundle/Service/AdventureSearch.php
src/AppBundle/Service/AdventureSerializer.php
src/AppBundle/Twig/AppExtension.php

As with @harkenn's PR, the new fields currently aren't displayed as filters. Also, the adventure creation form is broken. However, the adventure edit form works just fine.

Make simple fields static

---

app/DoctrineMigrations/Version20170724185627.php
app/DoctrineMigrations/Version20180000000000.php
app/Resources/views/adventure/show.html.twig
src/AppBundle/Command/AppElasticsearchReindexCommand.php
src/AppBundle/DataFixtures/ORM/RandomAdventureData.php
src/AppBundle/Entity/Adventure.php
src/AppBundle/Entity/AdventureDocument.php
src/AppBundle/Field/FieldProvider.php
src/AppBundle/Form/AdventureType.php
src/AppBundle/Service/AdventureSearch.php
src/AppBundle/Service/AdventureSerializer.php

This adds the "part of" field and uses it in our big, yet to execute, data migration.
It also renames the migration so it stays at the very end.
The last thing I want to work on is transferring the current logging system to the DataDog bundle. 
I'd intend to update production tomorrow (24/7/17).
I have the day off and will be able to fix potential problems.
This would conclude our move to the static data model and will allow us to work on new features and search improvements once again.

Feature/"part of" field

---

src/AppBundle/Command/AppMigrateDataModelCommand.php

This should help avoid confusion @jsaugustyn.

Move data migration into command to avoid confusion

---

app/Resources/webpack/adventure.js
src/AppBundle/Form/AdventureType.php

Minor bugfix which disables adding new values to fields where it isn't supported.

BugFix/Don't allow to add new values to fields where it isn't supported

---

app/config/config.yml
app/config/services.yml
src/AppBundle/Command/AppElasticsearchReindexCommand.php
src/AppBundle/Listener/SearchIndexUpdater.php
src/AppBundle/Service/AdventureSearch.php
src/AppBundle/Service/ElasticSearch.php

This logs ElasticSearch warnings and errors. To do so, a new *ElasticSearch* service is introduced which provides the ElasticSearch client with logging enabled.

Feature/Log ElasticSearch errors

---

src/AppBundle/Command/AppMigrateDataModelCommand.php

I'm pretty sure I had already done this, but I must've lost it between my many branches.

Also migrate partOf column.

---

app/config/config_prod.yml
app/config/parameters.yml.dist
src/AppBundle/Command/AppMigrateDataModelCommand.php

develop -> master

---

src/AppBundle/Listener/SearchIndexUpdater.php

This fixes the index update. It also adds an assertion that makes sure that no matter what, the index can't break due to this problem again.
Verified this is working locally.
EDIT: I could've created this PR directly against master, I suppose.
EDIT 2: After this is merged, create a new pull request to merge this into master, Also make sure you have added the following to  `app/config/parameters.yml` (from #93):
```yml
error_email_addresses:
- cmfcmf.flach@gmail.com
- ...
```

Make sure not to insert null as id.

---

src/AppBundle/Entity/Adventure.php

Allow 0 as min./max. starting level

---

src/AppBundle/Field/FieldProvider.php
src/AppBundle/Form/AdventureType.php

Correct foundIn text description

---

app/Resources/views/adventure/show.html.twig
app/Resources/webpack/sass/adventure.scss

Make notable items and common monsters adjacent, move BBEG above

---

app/Resources/views/adventure/index.html.twig

Clears all filters, retains the search query.
refs #155

Add button to clear all filters

---

app/Resources/views/adventure/search_results.html.twig

Improve starting level range display for non-ranges

---

app/Resources/webpack/adventure.js

I know the JavaScript file isn't getting more readable - but I also don't want to spend too much time if all of it eventually goes away due to a new frontend.
closes #148

Fix issue when the modal is closed other than by using the add button

---

app/Resources/views/adventure/new.html.twig
app/Resources/views/base.html.twig
app/Resources/webpack/sass/style.scss

This adds a bunch of links and explanation to the site's footer, closes #146.

Add links to footer

---

app/Resources/views/adventure/search_results.html.twig

Replace battle maps with number of pages in search results

---

app/Resources/views/adventure/show.html.twig

Changes for feature request #215

Add adventure name in html title per issue #215.

---

CONTRIBUTING.md
README.md
Vagrantfile

This fixes #250 and #251 (@j-frost).
- `README.md`:
- Mention test-user fixture
- Condense "Running in Production" section (remove mentions of Apache2)
- Add "Contributing" section
- `CONTRIBUTING.md`: Added contribution guidelines
- `Vagrantfile`:
- Correctly add `cd /vagrant` (for `ubuntu` as well as `vagrant` user)
- Make sure to always install NPM 5.x
- Be more quiet when `apt-get`-installing

Improve onboarding/contribution process and Vagrant box

---

app/Resources/views/adventure/_details.html.twig
app/Resources/views/adventure/_reviews.html.twig
app/Resources/views/adventure/index.html.twig
app/Resources/views/adventures/index.html.twig
app/Resources/views/adventures/search_filters.html.twig
app/Resources/views/adventures/search_results.html.twig
app/Resources/views/adventures/search_results_header.html.twig
app/Resources/views/base.html.twig
app/Resources/views/change_request/new.html.twig
app/Resources/views/footer.html.twig
app/Resources/views/header.html.twig
app/Resources/views/profile/base.html.twig
app/Resources/views/profile/overview.html.twig
app/Resources/webpack/js/adventures.js
app/Resources/webpack/js/index.js
app/Resources/webpack/js/reviews.js
app/Resources/webpack/sass/_adventure.scss
app/Resources/webpack/sass/_adventures.scss
app/Resources/webpack/sass/_filter.scss
app/Resources/webpack/sass/_sidebar.scss
app/Resources/webpack/sass/_tags.scss
app/Resources/webpack/sass/_variables.scss
app/Resources/webpack/sass/style.scss
package-lock.json
package.json
src/AppBundle/Controller/AdventureController.php
src/AppBundle/Service/AdventureSearch.php
src/AppBundle/Twig/AppExtension.php
tests/AppBundle/Controller/ProfileControllerTest.php

This PR fixes several issues with the new design. Most importantly, this makes the new design usable on mobile devices and fixes multiple reported and un-reported issues (fixes #269, fixes #264, fixes #258, fixes #266, fixes #144). I also added a cookie consent warning (let me know if you have feedback regarding that). I'm not too happy with how the adventure detail page looks in between mobile- and desktop-sized viewports. If you have any feedback regarding that, I'll try to improve it further.
This PR should bring us a lot closer to actually rolling out the new design.

Design Improvements

---

phpunit.xml.dist
src/AppBundle/DataFixtures/ORM/MonsterData.php
src/AppBundle/DataFixtures/ORM/MonsterTypeData.php
src/AppBundle/Field/Field.php
tests/AppBundle/DataFixtures/TestFixturesLoadable.php
tests/AppBundle/Field/FieldProviderTest.php
tests/AppBundle/Field/FieldTest.php
tests/AppBundle/Twig/AppExtensionTest.php

This adds tests for fixtures, the field provider, fields, and the bool2str Twig extension.

Add more tests

---

.travis.yml
app/AppKernel.php
app/config/config.yml
app/config/security.yml
app/config/services.yml
composer.json
composer.lock

This updates Symfony to 3.4 LTS (http://symfony.com/roadmap/3.4).

Update to Symfony 3.4 LTS

---

.travis.yml
README.md
Vagrantfile
app/Resources/views/adventure/_details.html.twig
app/Resources/views/adventure/_reviews.html.twig
app/Resources/views/adventures/search_filters.html.twig
app/Resources/views/adventures/search_results_tags.html.twig
app/Resources/views/base.html.twig
app/Resources/webpack/js/vendor.js
composer.lock
package-lock.json
package.json
phpunit.xml.dist
scripts/vagrant-docker/Dockerfile
src/AppBundle/Twig/AppExtension.php
src/AppBundle/Twig/AuditExtension.php
tests/BrowserTestCase.php
var/SymfonyRequirements.php
webpack.config.js

I updated Symfony to the latest 3.4.x version, and also all other PHP dependencies that reported security vulnerabilities. I also updated the Vagrantfile to use OpenJDK instead of the no longer working OracleJDK PPA. JS dependencies have been upgraded as well.
Travis runs through successfully again.

Update dependencies, add Docker support with Vagrant

---

app/DoctrineMigrations/Version20200515165843.php
app/Resources/views/adventure/_details.html.twig
app/Resources/webpack/js/adventures_filter/Filters.jsx
src/AppBundle/Command/AppElasticsearchReindexCommand.php
src/AppBundle/DataFixtures/ORM/RandomAdventureData.php
src/AppBundle/Entity/Adventure.php
src/AppBundle/Entity/AdventureDocument.php
src/AppBundle/Field/FieldProvider.php
src/AppBundle/Form/Type/AdventureType.php
src/AppBundle/Service/AdventureSearch.php
src/AppBundle/Service/Serializer.php
tests/AppBundle/Field/FieldProviderTest.php
tests/AppBundle/Service/SerializerTest.php
tests/Browser/NewAdventureTest.php

This PR adds a publication year field as requested in #129.
<a href="https://gitpod.io/#https://github.com/AdventureLookup/AdventureLookup/pull/309"><img src="https://gitpod.io/api/apps/github/pbs/github.com/cmfcmf/AdventureLookup.git/6a7b324e3e6342843d23ea580b1561311689e2df.svg" /></a>

Add publication year field

---

Vagrantfile

I noticed that the mysql and elasticsearch services were not started when using Vagrant with Docker. This PR fixes that by starting the two services when running `vagrant up`. I also had to move the provisioner below the "initial" provisioner, so that it runs after installing dependencies.
<a href="https://gitpod.io/#https://github.com/AdventureLookup/AdventureLookup/pull/302"><img src="https://gitpod.io/api/apps/github/pbs/github.com/cmfcmf/AdventureLookup.git/1795f1821d825ed038fd31adce8663016e5aef4a.svg" /></a>

Always start mysql and elasticsearch services when using Vagrant+Docker

---

app/Resources/webpack/js/adventures.js
app/Resources/webpack/js/adventures_filter/Filters.jsx
app/Resources/webpack/js/adventures_filter/Root.jsx
app/Resources/webpack/js/adventures_filter/SearchBox.jsx
app/Resources/webpack/js/adventures_filter/SearchTips.jsx
app/Resources/webpack/sass/_adventures.scss
app/Resources/webpack/sass/_general.scss
src/AppBundle/Field/FieldProvider.php
src/AppBundle/Service/AdventureSearch.php

These are some initial attempts to improve the search query field behavior. I will go into more detail after testing this for a bit.
I have temporarily deployed this branch to dev.adventurelookup.com to play around with it.
<a href="https://gitpod.io/#https://github.com/AdventureLookup/AdventureLookup/pull/308"><img src="https://gitpod.io/api/apps/github/pbs/github.com/cmfcmf/AdventureLookup.git/85ffcb18284b0235fe03647fcd3af4b7cee715d0.svg" /></a>

Improve query field search behavior

---

app/Resources/webpack/js/adventures_filter/SearchTags.jsx
app/Resources/webpack/sass/_adventures.scss

Closes #340 
<a href="https://gitpod.io/#https://github.com/AdventureLookup/AdventureLookup/pull/346"><img src="https://gitpod.io/api/apps/github/pbs/github.com/wetterlicht/AdventureLookup.git/e722aa3e6a9e56dc70d8de494cbd0df733d6909c.svg" /></a>
<a href="https://gitpod.io/#https://github.com/AdventureLookup/AdventureLookup/pull/346"><img src="https://gitpod.io/api/apps/github/pbs/github.com/wetterlicht/AdventureLookup.git/e722aa3e6a9e56dc70d8de494cbd0df733d6909c.svg" /></a>

Clear All Filters Button

---

.travis.yml
app/Resources/webpack/js/adventure.js
app/Resources/webpack/js/adventure_list.js
app/Resources/webpack/js/adventures.js
app/Resources/webpack/js/adventures_filter/SearchTags.jsx
app/Resources/webpack/js/index.js
app/Resources/webpack/js/paginated_list_group.js
app/Resources/webpack/js/reviews.js
app/Resources/webpack/js/vendor.js
package-lock.json
package.json

I dont know much of anything about symphony so don't know if this can be set up to hook to on-save or something within the encore dev command. For the time being a "prettier" script has been added for developer convenience, `targeting app/Resources/**/*.jsx`
<a href="https://gitpod.io/#https://github.com/AdventureLookup/AdventureLookup/pull/327"><img src="https://gitpod.io/api/apps/github/pbs/github.com/sinh343/AdventureLookup.git/10aca155f9d3ee73b6cffd815f46021a5af0ae6c.svg" /></a>

added prettier dependency and script for react code.

---

app/Resources/views/footer.html.twig
app/Resources/webpack/sass/_footer.scss
app/Resources/webpack/sass/style.scss

Closes #321 
My attempt at improving the footer design using existing adl colors. Admittedly not my strong suit :)
<a href="https://gitpod.io/#https://github.com/AdventureLookup/AdventureLookup/pull/349"><img src="https://gitpod.io/api/apps/github/pbs/github.com/wetterlicht/AdventureLookup.git/d213055437be8446cb76d814de752ec29c5f90a4.svg" /></a>

Footer design

---

.gitpod.Dockerfile
Vagrantfile
app/Resources/views/adventures/opensearch.xml.twig
app/Resources/views/base.html.twig
app/config/config.yml
app/config/config_test.yml
src/AppBundle/Controller/AdventureController.php
src/AppBundle/Form/Type/AdventureType.php
src/AppBundle/Listener/SearchIndexUpdater.php

<a href="https://gitpod.io/#https://github.com/AdventureLookup/AdventureLookup/pull/388"><img src="https://gitpod.io/api/apps/github/pbs/github.com/cmfcmf/AdventureLookup.git/78fb9858edb139984b44a65e0c1af9e015d6c646.svg" /></a>

Add support for OpenSearch, set samesite attribute for session cookie, minor ElasticSearch fixes
